### ISSUE TITLE
Does not work when running in docker

### ISSUE THREAD

**Issue by tomasvanagas** [ParisNeo/lollms_legacy#14]
sudo docker-compose build
Building lollms
Sending build context to Docker daemon  7.532MB
Step 1/19 : ARG BASE_IMAGE
Step 2/19 : FROM ${BASE_IMAGE}
 ---> 3898600d93b6
Step 3/19 : WORKDIR /app
 ---> Using cache
 ---> 071b55924bcf
Step 4/19 : COPY requirements.txt /app/requirements.txt
 ---> Using cache
 ---> 11ab1970e0e9
Step 5/19 : RUN apt update
 ---> Using cache
 ---> 805308ce65c1
Step 6/19 : RUN apt install -y git
 ---> Using cache
 ---> 749a4788d560
Step 7/19 : RUN pip install --trusted-host pypi.python.org -r requirements.txt
 ---> Using cache
 ---> c0f0d81ffd96
Step 8/19 : COPY ./elf_docker_cfg /app/elf_docker_cfg
 ---> Using cache
 ---> efaf30b9abda
Step 9/19 : COPY ./lollms /app/lollms
 ---> Using cache
 ---> 4096a761e1f4
Step 10/19 : COPY ./README.md /app/README.md
 ---> Using cache
 ---> 17fbdfac0277
Step 11/19 : COPY ./MANIFEST.in /app/MANIFEST.in
 ---> Using cache
 ---> 876b9b80a3ef
Step 12/19 : COPY ./LICENSE /app/LICENSE
 ---> Using cache
 ---> d1b6654abc65
Step 13/19 : COPY ./requirements_dev.txt /app/requirements_dev.txt
 ---> Using cache
 ---> 6eaa628d0a81
Step 14/19 : COPY ./requirements.txt /app/requirements.txt
 ---> Using cache
 ---> 1c7197f962ff
Step 15/19 : COPY ./setup.py /app/setup.py
 ---> Using cache
 ---> 98d738e0b7f5
Step 16/19 : COPY ./zoos /app/zoos
 ---> Using cache
 ---> c33597a59a91
Step 17/19 : COPY ./configs /app/configs
 ---> Using cache
 ---> bde2a43213dd
Step 18/19 : RUN pip install -e .
 ---> Using cache
 ---> 01f14120b9a7
Step 19/19 : CMD ["lollms-elf","--host","0.0.0.0", "--port", "9601", "--default_cfg_path", "/app/elf_docker_cfg/config_paths.yaml"]
 ---> Using cache
 ---> 8bcfc594cba2
Successfully built 8bcfc594cba2
Successfully tagged lollms_lollms:latest

sudo docker-compose up
Starting lollms_lollms_1 ... done
Attaching to lollms_lollms_1
lollms_1  | fatal: not a git repository (or any of the parent directories): .git
lollms_1  | fatal: not a git repository (or any of the parent directories): .git
lollms_1  | fatal: not a git repository (or any of the parent directories): .git
lollms_1  | fatal: not a git repository (or any of the parent directories): .git
lollms_1  |          _             _            _             _            _   _         _        
lollms_1  |         _\ \          /\ \         _\ \          _\ \         /\_\/\_\ _    / /\      
lollms_1  |        /\__ \        /  \ \       /\__ \        /\__ \       / / / / //\_\ / /  \     
lollms_1  |       / /_ \_\      / /\ \ \     / /_ \_\      / /_ \_\     /\ \/ \ \/ / // / /\ \__  
lollms_1  |      / / /\/_/     / / /\ \ \   / / /\/_/     / / /\/_/    /  \____\__/ // / /\ \___\ 
lollms_1  |     / / /         / / /  \ \_\ / / /         / / /        / /\/________/ \ \ \ \/___/ 
lollms_1  |    / / /         / / /   / / // / /         / / /        / / /\/_// / /   \ \ \       
lollms_1  |   / / / ____    / / /   / / // / / ____    / / / ____   / / /    / / /_    \ \ \      
lollms_1  |  / /_/_/ ___/\ / / /___/ / // /_/_/ ___/\ / /_/_/ ___/\/ / /    / / //_/\__/ / /      
lollms_1  | /_______/\__\// / /____\/ //_______/\__\//_______/\__\/\/_/    / / / \ \/___/ /       
lollms_1  | \_______\/    \/_________/ \_______\/    \_______\/            \/_/   \_____\/        
lollms_1  |          _            _             _                                                 
lollms_1  |         /\ \         _\ \          /\ \                                               
lollms_1  |        /  \ \       /\__ \        /  \ \                                              
lollms_1  |       / /\ \ \     / /_ \_\      / /\ \ \                                             
lollms_1  |      / / /\ \_\   / / /\/_/     / / /\ \_\                                            
lollms_1  |     / /_/_ \/_/  / / /         / /_/_ \/_/                                            
lollms_1  |    / /____/\    / / /         / /____/\                                               
lollms_1  |   / /\____\/   / / / ____    / /\____\/                                               
lollms_1  |  / / /______  / /_/_/ ___/\ / / /                                                     
lollms_1  | / / /_______\/_______/\__\// / /                                                      
lollms_1  | \/__________/\_______\/    \/_/                                                       
lollms_1  | Trying to use Configuration at :/app/elf_docker_cfg/config_paths.yaml
lollms_1  | /app/elf_docker_cfg/config_paths.yaml found!
lollms_1  | Execution path : /app
lollms_1  | Local zoos folder found
lollms_1  | ----------------------Paths information-----------------------
lollms_1  | personal_path:/app/elf_docker_cfg/personal
lollms_1  | personal_configuration_path:/app/elf_docker_cfg/personal/configs
lollms_1  | personal_databases_path:/app/elf_docker_cfg/personal/databases
lollms_1  | personal_models_path:/app/elf_docker_cfg/personal/models
lollms_1  | personal_user_infos_path:/app/elf_docker_cfg/personal/user_infos
lollms_1  | personal_trainers_path:/app/elf_docker_cfg/personal/trainers
lollms_1  | personal_trainers_path:/app/elf_docker_cfg/personal/trainers/gptqlora
lollms_1  | personal_data_path:/app/elf_docker_cfg/personal/data
lollms_1  | custom_personalities_path:/app/elf_docker_cfg/personal/custom_personalities
lollms_1  | -------------------------------------------------------------
lollms_1  | ----------------------Zoo information-----------------------
lollms_1  | bindings_zoo_path:/app/zoos/bindings_zoo
lollms_1  | personalities_zoo_path:/app/zoos/personalities_zoo
lollms_1  | extensions_zoo_path:/app/zoos/extensions_zoo
lollms_1  | models_zoo_path:/app/zoos/models_zoo
lollms_1  | -------------------------------------------------------------
lollms_1  | Bindings zoo found in your personal space.
lollms_1  | Pulling last personalities zoo
lollms_1  | Personalities zoo found in your personal space.
lollms_1  | Pulling last personalities zoo
lollms_1  | Extensions zoo found in your personal space.
lollms_1  | Pulling last Extensions zoo
lollms_1  | Models zoo found in your personal space.
lollms_1  | Pulling last Models zoo
lollms_1  | No binding selected
lollms_1  | Couldn't load personality. Please verify your configuration file at /app/elf_docker_cfg/personal/configs or use the next menu to select a valid personality
lollms_1  | Binding returned this exception : Could not find the personality package:/app/zoos/personalities_zoo/generic/lollms
lollms_1  | Traceback (most recent call last):
lollms_1  |   File "/app/lollms/app.py", line 207, in mount_personality
lollms_1  |     personality = PersonalityBuilder(self.lollms_paths, self.config, self.model, self, callback=callback).build_personality(id)
lollms_1  |   File "/app/lollms/personality.py", line 1795, in build_personality
lollms_1  |     self.personality = AIPersonality(
lollms_1  |   File "/app/lollms/personality.py", line 172, in __init__
lollms_1  |     raise ValueError(f"Could not find the personality package:{self.personality_package_path}")
lollms_1  | ValueError: Could not find the personality package:/app/zoos/personalities_zoo/generic/lollms
lollms_1  | 
lollms_1  | personalities_zoo_path: /app/zoos/personalities_zoo
lollms_1  | Personalities:['generic/lollms']
lollms_1  | Active personality id:-1
lollms_1  |  * Serving Flask app 'lollms.apps.elf'
lollms_1  |  * Debug mode: off
lollms_1  | WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
lollms_1  |  * Running on all addresses (0.0.0.0)
lollms_1  |  * Running on http://127.0.0.1:9601
lollms_1  |  * Running on http://172.19.0.2:9601
lollms_1  | Press CTRL+C to quit

**Comment by ParisNeo** [comment]
Hi there. In fact I didn't update the docker for ages. I think it is now outdated and I need to find time to make it work again.

**Comment by gitwittidbit** [comment]
Has docker been updated? I'm getting a "ModuleNotFoundError: No module named 'lollms'"...
